-- Concatenates src/ modules into one game-loadable file: Civ 5 mod
-- Lua has no require(), so modules are registered as functions and
-- resolved by an inlined _require.
local FILES = {
  "src.json",
  "src.adapter",
  "src.extractors",
  "src.logger",
  "src.main",
}

local PRELUDE = [[
-- Generated by tools/build.lua - DO NOT EDIT. Sources: src/*.lua
local modules = {}
local function register(name, fn) modules[name] = fn end
local function _require(name)
  if type(modules[name]) == "function" then modules[name] = modules[name]() end
  return modules[name]
end
]]

local ENTRY = [[
_require("src.main").start({
  Game = Game,
  Players = Players,
  Teams = Teams,
  Map = Map,
  GameInfo = GameInfo,
  GameDefines = GameDefines,
  PreGame = PreGame,
  GameEvents = GameEvents,
  Modding = Modding,
  print = print,
})
]]

local M = {}

local function moduleSource(name)
  local path = name:gsub("%.", "/") .. ".lua"
  local file = assert(io.open(path, "r"))
  local source = file:read("*a")
  file:close()
  return (source:gsub("require%(", "_require("))
end

function M.generate()
  local parts = { PRELUDE }
  for _, name in ipairs(FILES) do
    table.insert(parts,
      ('register(%q, function()\n%send)\n'):format(name, moduleSource(name)))
  end
  table.insert(parts, ENTRY)
  return table.concat(parts, "\n")
end

function M.write(path)
  local file = assert(io.open(path, "w"))
  file:write(M.generate())
  file:close()
end

if arg and arg[0] and arg[0]:find("build%.lua$") then
  local out = arg[1] or "dist/CivNarrativeLogger.lua"
  os.execute(('mkdir -p %q'):format(out:match("^(.*)/") or "."))
  M.write(out)
  print("wrote " .. out)
end

return M
